//js file where all game data will live and be referenced from
const Data = {
    features: {
        categories: 1,
        clues: 1,
    },

    categories: {
        "7-Letter Words": 1,
        "Holidays": 2,
        "Bodies of Water": 3,
        "Vegetables": 4,
        "Medical Diseases": 5,
        "U.S. Cities": 6,
        "Ice Hockey": 7,
        "The World": 8,
        "Safari": 9,
        "Greek Mythology": 10,
        "Storms": 11,
        "Movies": 12,
        "Final Question": 13
    },

    clues: [
        {
            question: "If a duck made a sound, you would say that it what?",
            pointValue: 100,
            answer: "quacked",
            categoryID: 1,
        },
        {
            question: "These may be left out for Santa Claus",
            pointValue: 200,
            answer: "cookies",
            categoryID: 1,
        },
        {
            question: "This group of people rob and attack ships at sea",
            pointValue: 300,
            answer: "pirates",
            categoryID: 1,
        },
        {
            question: "A popular 80's song titled, 'Its (blank) Men!'",
            pointValue: 400,
            answer: "raining",
            categoryID: 1,
        },
        {
            question: "This extinct, large-tusked mammal thrived during the heart of the Ice Age Era",
            pointValue: 500,
            answer: "mammoth",
            categoryID: 1,
        },
        {
            question: "On this night, children may dress up as ghosts, goblins, or ghouls",
            pointValue: 100,
            answer: "Halloween",
            categoryID: 2,
        },
        {
            question: "You may wake up to find presents under the tree on thsi holiday",
            pointValue: 200,
            answer: "Christmas",
            categoryID: 2,
        },
        {
            question: "This holiday weekened has been noted as the busiest travel period of the year",
            pointValue: 300,
            answer: "Thanksgiving",
            categoryID: 2,
        },
        {
            question: "Celebrated by Christians, as this holiday represents the ressurection of Jesus Christ",
            pointValue: 400,
            answer: "Easter",
            categoryID: 2,
        },
        {
            question: "On the night of this holiday, the sky is decorated with bright pops of color",
            pointValue: 500,
            answer: "Fourth of July",
            categoryID: 2,
        },
        {
            question: "The ocean that borders the East Coast",
            pointValue: 100,
            answer: "Atlantic",
            categoryID: 3,
        },
        {
            question: "This ocean borders the West Coast",
            pointValue: 200,
            answer: "Pacific",
            categoryID: 3,
        },
        {
            question: "The Nile is the longest (blank) in the world",
            pointValue: 300,
            answer: "river",
            categoryID: 3,
        },
        {
            question: "Shrek the Ogre calls this type of forested wetland his home",
            pointValue: 400,
            answer: "swamp",
            categoryID: 3,
        },
        {
            question: "The name of this sea's turquoise waters is 10x saltier than ordinary seawater",
            pointValue: 500,
            answer: "dead sea",
            categoryID: 3,
        },
        {
            question: "This vegetable may require husking before eating",
            pointValue: 100,
            answer: "corn",
            categoryID: 4,
        },
        {
            question: "A versatile vegetable: may be mashed, fried, or baked",
            pointValue: 200,
            answer: "potato",
            categoryID: 4,
        },
        {
            question: "The Christmas ornaments of vegetables. Eaten raw or cooked",
            pointValue: 300,
            answer: "bell pepper",
            categoryID: 4,
        },
        {
            question: "A nutrient-rich leafy green whose name rhymes with an Ivy League university",
            pointValue: 400,
            answer: "kale",
            categoryID: 4,
        },
        {
            question: "High in vitamin A, this vegetable is a great component in heart soups and stews",
            pointValue: 500,
            answer: "carrots",
            categoryID: 4,
        },
        {
            question: "Most commonly seen in children, this illness causes 250-500 tiny itchy spots",
            pointValue: 100,
            answer: "chicken pox",
            categoryID: 5,
        },
        {
            question: "A contagious respiratory disease that infects millions of people annually",
            pointValue: 200,
            answer: "flu" || "influenza",
            categoryID: 5,
        },
        {
            question: "Eradicated in 1980, this disease was fatal, causing pus-filled blisters all over the body",
            pointValue: 300,
            answer: "smallpox",
            categoryID: 5,
        },
        {
            question: "Affects the eye, turning the sclera a pinkish color",
            pointValue: 400,
            answer: "pink eye" || "conjunctivitis",
            categoryID: 5,
        },
        {
            question: "In the 1300's, this disease wiped out 75-200 million people. Referred to as 'The Black Death'",
            pointValue: 500,
            answer: "Bubonic Plague",
            categoryID: 5,
        },
        {
            question: "Starbucks originated in the same city the Space Needle is found",
            pointValue: 100,
            answer: "Seattle",
            categoryID: 6,
        },
        {
            question: "Home to Fenway Park, MIT, and the first zip code",
            pointValue: 200,
            answer: "Boston",
            categoryID: 6,
        },
        {
            question: "City where you can find 'The Strip'",
            pointValue: 300,
            answer: "Las Vegas" || "Vegas",
            categoryID: 6,
        },
        {
            question: "The capital city of the United States",
            pointValue: 400,
            answer: "DC" || "District of Columbia",
            categoryID: 6,
        },
        {
            question: "City famous for its warm climate, white sand beaches, Cuban coffee, and Latin-American influences",
            pointValue: 500,
            answer: "Miami",
            categoryID: 6,
        },
        {
            question: "Game that is the national winter sport of Canada",
            pointValue: 200,
            answer: "hockey" || "ice hockey",
            categoryID: 7,
        },
        {
            question: "In hockey, players must try to shoot the (blank) into the net",
            pointValue: 400,
            answer: "puck",
            categoryID: 7,
        },
        {
            question: "Number of minutes in a single period of professional ice hockey",
            pointValue: 600,
            answer: "20" || "twenty",
            categoryID: 7,
        },
        {
            question: "Which retired NHL player said this famous phrase: 'You miss 100% of the shots you don't take'",
            pointValue: 800,
            answer: "Wayne Gretzky" || "Gretzky",
            categoryID: 7,
        },
        {
            question: "Which NHL team holds the most Stanley Cup titles",
            pointValue: 1000,
            answer: "Montreal Canadiens" || "Montreal" || "Canadiens",
            categoryID: 7,
        },
        {
            question: "Country famous for the Great Pyramids and Sahara Desert",
            pointValue: 200,
            answer: "Egypt",
            categoryID: 8,
        },
        {
            question: "North American country notorious for their poutine, polite citizens, and uninhabited land",
            pointValue: 400,
            answer: "Canada",
            categoryID: 8,
        },
        {
            question: "A nation known for its people's vodka consumption",
            pointValue: 600,
            answer: "Russia",
            categoryID: 8,
        },
        {
            question: "The first king of this nation was a Viking named Harold Fairhair",
            pointValue: 800,
            answer: "Norway",
            categoryID: 8,
        },
        {
            question: "This South-American country is home to both the lowest and highest points of the Southern Hemisphere",
            pointValue: 1000,
            answer: "Argentina",
            categoryID: 8,
        },
        {
            question: "Be careful, this animal may swing down from a vine and steal your banana",
            pointValue: 200,
            answer: "monkey",
            categoryID: 9,
        },
        {
            question: "Animal with a long neck and blotched spots",
            pointValue: 400,
            answer: "giraffe",
            categoryID: 9,
        },
        {
            question: "Often referred to as the 'King of the Jungle'",
            pointValue: 600,
            answer: "lion",
            categoryID: 9,
        },
        {
            question: "Broad chest and shoulders, large hands, black face, and prominent nostrils",
            pointValue: 800,
            answer: "gorilla",
            categoryID: 9,
        },
        {
            question: "This animal has an average weight of 3.5 tons, with a bulky body and stumpy legs",
            pointValue: 1000,
            answer: "hippopotamus" || "hippo",
            categoryID: 9,
        },
        {
            question: "Greek God of the Sky, chief of the Greek Deity, represented by lighting bolts",
            pointValue: 200,
            answer: "Zeus",
            categoryID: 10,
        },
        {
            question: "This place was thought to be the home of the Greek Gods and Goddesses",
            pointValue: 400,
            answer: "Mount Olympus",
            categoryID: 600,
        },
        {
            question: "God of the sea, symbolized by his Trident",
            pointValue: 600,
            answer: "Poseidon",
            categoryID: 10,
        },
        {
            question: "Goddess of War, said to be Zeus's favorite child",
            pointValue: 800,
            answer: "Athena",
            categoryID: 10,
        },
        {
            question: "Zeus's son, who was born a demi-god with incredible strength and stamina",
            pointValue: 1000,
            answer: "Hercules",
            categoryID: 10,
        },
        {
            question: "Featured in the movie 'Twister'",
            pointValue: 200,
            answer: "tornado",
            categoryID: 11,
        },
        {
            question: "Sometimes you can hear this storm before it reaches you",
            pointValue: 400,
            answer: "thunderstorm" || "thunder",
            categoryID: 11,
        },
        {
            question: "Occurs during winter months, characterized by heavy snow and low visibility",
            pointValue: 600,
            answer: "blizzard",
            categoryID: 11,
        },
        {
            question: "Typically the result of prolonged heavy rain",
            pointValue: 800,
            answer: "flood",
            categoryID: 11,
        },
        {
            question: "This type of natural disaster can split land in two",
            pointValue: 1000,
            answer: "earthquake",
            categoryID: 11,
        },
        {
            question: "Harry Potter's arch nemesis",
            pointValue: 200,
            answer: "Voldemort",
            categoryID: 12,
        },
        {
            question: "Steven Spielberg directed which dinosaur movie",
            pointValue: 400,
            answer: "Jurassic Park",
            categoryID: 12,
        },
        {
            question: "In Pirates of the Caribbean, who is Johnny Depp's character",
            pointValue: 600,
            answer: "Captain Jack Sparrow" || "Jack Sparrow",
            categoryID: 12,
        },
        {
            question: "Al Pacino is known for his role in this movie about the rise and fall of an Italian Mafia family",
            pointValue: 800,
            answer: "The Godfather",
            categoryID: 12,
        },
        {
            question: "Elijiah Wood, Orlando Bloom, and Viggo Mortensen starred in what film series",
            pointValue: 1000,
            answer: "Lord of the Rings",
            categoryID: 12,
        },
    ]

}